Vagrant.configure("2") do |config|

  config.vm.define "bastion" do |bastion|
    bastion.vm.box = "${bastion_box_name}"
    bastion.vm.box_version = "${bastion_box_version}"

    bastion.vm.network "public_network", bridge: "${def_bridge_name}"
    bastion.vm.disk :disk, name: "data", file: "${data_disk_path}", size: "20GB", primary: false
   
    bastion.vm.cloud_init :user_data do |cloud_init|
      cloud_init.content_type = "text/cloud-config"
      cloud_init.path = "${cloud_config_path}"
    end

    bastion.vm.provider "virtualbox" do |vb|
      vb.name = "${bastion_vm_name}"
      vb.gui = false
      vb.memory = "${bastion_memory_size}"
      vb.customize [ "guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold", 1000 ]
    end

    # remove default route on nat interface as 
    # interfaces will be reconfigured
    # config.vm.provision "shell",
    #   run: "always",
    #   inline: "ip route del default via 10.0.2.2 || true"
  end
end
