dist: bionic
sudo: required
language: bash
services:
- docker
env:
  global:
  - DOCKER_REPO=appbricks
  - secure: zHleoKca/Omcwis2kebQVm4HncNwFwDN14cXVC7af+qsk15OtIlMG9H8laCwUDpxdTd6I1K0oUxy/tjFOahhPhFwHguvT3+ufpax9uNXSUoeSmeJk76SC3WeLit5dWB25dv1032ol5FrPbZ9zLy8lCYTTNQWrk95QdbfRp10fp4/kKwjujlQ9CEJAI8HFmTdbWuDIyjW+n/5Zl9L64uqG1Secw8fedK/f+KDiyrF725woFzltaQ/vLeX1ePyXdFg9bZC4NBeen9ODNo50TZg6SVSsTKwUJmpM6l+Mu0Mb4nSXmXhDDO9BXGY4w8vfDJUu3ipX3lO5JviIaMwUrurgXDKzXvCkQLdKGmJCCl5VcCny+2Hi8cj7OVXm7TJx2FR6rWjpf8mppD5iTI6Xs0hQEakKF3yDQhfYsNsKOwjV2gRzMrfC+fJ4hz2pwkirZwBZPzj5CsSggoizyKSUdmRWSRHw8ltaJ7IQvoh5426fTGUWcZeBQEYGy1AVASk1N6qKiYQuxq3Lgs7MA785CwbQMwAMbh9Udzye3JG2YzssMQYvGxrCsyPFvRns7f12GAUyS+Z+3Fn49xBE5Nvjfa2GRTKoZPteMHd3BGve0PgATHCItpXBjjJxbEho5nUZXEHSP3DP5WigPzEVXK7WXyoYSTpTifF1ynu0ekHNLNNUhA=
  - secure: tdUFX6fmacEqvqMASqvBtihGpHp0zyoqr+/ExOsG7wTEcneLXrT7ITM10W+GjszaYz59RzrAi0UWY/YEt76j5g7V6ywqGUve0ZKA9vSkkS/9b4oqExA6DFSIhe5qPekkD6e4FsFfphKD3xu9VsqtLPODW1jV7sOLhAtJnthpwY8jfREvBPqele59iKafKCaReC97ag4tzAhp2guOLizzvlBXygz5PYVdWNlZYB0AzeeRn1LhL948tnw47cbOLatqTxA9Rra24/5EvpL6Y0mYJYU8DTD6w4Gzk/ALt818vbxMc9BCCttLN10IjlxzXz7P9gmY20VWEZtM2XACEZDt/68HB16GYbx6gvQWLnOc/hKjaQqttxwvJWCXPkajurfAX7AoT1jfa4LbdwA2PQI5+SnZWVSzeoPzaG2Ov4Sq6pdcCkg415FKSb68mbrWertNNkgcTcgzqckAiENeCt3ftKGhWb+wuZWYDnPIgI7mW3Py2tiRR+bmhgIXUNNs034CxoDt8MI2iBvQKcU4JZNadYNTIasaw124lG0bUVF5Cadd64DMbd8NVSzDRuVoNbpK+HTthhohYRDhSean4XoUyylh1uG8gdF8vC36OftfJfdz2MU2PK3yHpez2egU1QeTZcvBcg9JLp5vgWe0iFzPiWRlzBXs1hzFxMW2+kvSaDI=
script:
- src/build/run-ci-build.sh
