dist: bionic
sudo: required
language: bash
services:
- docker
env:
  global:
  - DOCKER_REPO=appbricks
  - secure: yjWEj9t4Tv+GhvVA4LTqyAbK7m9hydwUvNAIYCo3jk+4oHEhPTu211wLAjSO7/czZ+ktH5q+WkKtYheGKB4H0oKOxSNepQQhDjFxRK2xlYAD2xuL8GJLGTyK7RrXQbeKETfdM3grLWsSj11yjev1GGfNMSxnJZfd/46P1htut8uZfqHtse2T3ik9XsnOp7s8wRIuFkSKFToI2/sUFcGFu8ZEfiO7VGZ4Q7hlgt0XoVzPqDDMX2fwsj1At9oBp6iCcL77tMkEbBYGhxsI46B62iaoQX0q29Zy5/pQR6zvzIq6qcvuhL9tHOfleGh6HHDxmtref1RJVJcBlWMmPIORqobtvPkFZR2Twg0xnkwWwBuHahWcrBgSMnWUHVltQYxvX0YAvNBrZ87kxK2QdRRprjhzgi4heO1/bMV58mJfmz/3OmDn04oeqibExrObbvt6tGTWc8QZ3ozb2W7J85uNZf7vGUZXFvFfwpfY0esltq1kpqrzneYvxSvhrRfkA7SYzQbnEZXZvsHj41hehmcZTz7Z5ACP4b7XYunv+/cJpoKn+iNtFxZ1oBJIvbJ6N15CBkKqhxcXQvAA/S6hgAhnqalJYYVYykGQ52tAuZIRmIf7mTS2w59dIAxds4aCs2nEXLCYRN3puU+hvRbWaRQfc/jBzn89siUDq9okljJdOb8=
  - secure: ZlWQ+0nsNG1m0GhTIBcVpRaB0wEA3eJzYJ5H2uwzNaIcqdrd9dJX2GgXveWCuqWXGHhA+Ku060Yn8xbOF9cu4T1u636E9q3bHa1lw5c9adfkm1RUZOiHVQWm01F5OsrYL8lf/fA5GCcJrStPl3mUUUclcfGpc5ojtqLPO5Xma0qJBoiIf9meSOJXTeSwZ4CKejWBGxix42yq5MD7jQh773kS5DIb3561KsHYSJ5kZxMHOeyj8fikPLxTQPehjwpk9+1JRQeS0uN2EcUIKcfrREZKA/1NA/rkDEAxWUdHus78RHoyHUG2w+JQUphm0hDw2//qxSmO9W/3ZYxjd803/LLkVNnOWKOLa3Kb/IrrsQnDTWJqaBZN/JVvjW566E4sYgZ91T+LYRYt0YD09w3Ju7eMJKGyuJiX9+8WARzzjk/kcReZ63kC6yz3y+q4AdoNBHItwmZN1E1RNAlpTcVtRo75BDa+zOe4Ahd00ZLbdOsF/8g8hd/H/1CC29Pi1XvfZ6LNd0mQ3KZH6blqOpz0Az2JLXr02nbd66cXkOBk4g6vTWL9L+z7FvlM6/AaGHZH2Zq4x0NrOEe95WhhgKPujUArZwq0fmPcn/cv1GD8r2X+8PuQzVN6I7+vLea8kJ4nL22pvVzbDEef0ZOY2lpWtbdPueIiuThZU7+/8b0AzJc=
script:
- src/build/run-ci-build.sh
