dist: bionic
sudo: required
language: bash
services:
- docker
env:
  global:
  - DOCKER_REPO=appbricks
  - secure: ON2eYZV8J0FpAd+z/HbYHhm/5HDyQ9Oma4HUtvGfetfU9KxOIZJwwe9uDSHognL4iL6kvscqMmc255o3M2DySa8P3+xy5Mrz/x+oU22Ok52+GMabx638sYW4DoibE7DAMHSHF4bQej2LgKt0rFARi5GlOfHPlFvYdbBDsDOhzWckyrHwv/k/iqhZGi1cRRKE9/quAMRvGABO/n5GC2972oDa5CGMNZw9/wDhoZLLd7Rd02pAUS+kx1N0yeg3xFK33oKvGgV/OL6jfwqWRhnXcM7nBCz0HmWOh0ljq/2XUF5t7BhC8x9DMHU+64svvd3jX60ecWdzcqWNPw54ZV9APQndeyk+9g5jCzRMJrRCR6FFv+//VriPjdC/HwA6QNvsGo2w63uFf/HAjNKIat6uCYF3dQQgH4UvW7IZddEvqX/7isR70l33I2SLDkdcjwQ8i1R6LIrbNGML67eRlWMyYS6H4RDaFh2c0/T5nsofO5H8GBK9gwPuR5L/lVwxl4wGC9HfJiJXykRXIlCBDiMj6NhEFovk54gurrbAi47F1WMrmEvbdNC3yeVRH2kdaYn7jAJ9J+6FP2IT3P1QnXIhIw6v+f3XhIWw2dmVBg2afD2myaJsq8Yf7PcHoCi0jXY69TSpRE9XAqU1nM23dok91yrkQ9S55VovTQ/Cep0vwf4=
  - secure: ziu1lH4UOEEWBzBxlkX+1qhA2BiRp+Uth3OWxLuOTUoxvv6PCkURmSqAuHKN/TDke2WmpsrYZL09GNhYz1VBN6qQ1ThxO0Ezj4yGlo4IhRvGIwvmtqvVz8dUjl0oJBkgNiDqKVO7ZMzUtRaMC92C0Wg5akcnVDpm9tWakhl1tt7H24f/eWopWk8whJlaHWIXf7liwScBInRCKoYG5tIpieB5xTqE/05IMGQFlHlj4SZ6swLkdCzSG/7D2FVA6KbPwQ0vbXsktGQrXk7yKRBryRcc7X07zfEDWv9r0LcCULGA41q/9ZAkRUV3BOfuh4Ub5NrIPD0Of0GvVX8FGhkR3bwKnQRDriTG8AVM3xs0voQo0Eu8LVrWST31/2UpWtkoOMju0uER5JguSK2EJs2doIFh9FGGfkdLRYgmHUIQJn01QoRNpXVjKGYTYsxYobP2jN/aSjN7aw3b31uVEHfnOXd1WiraYQio0ywCS3TUIV65tRC/ypr+n9znX1weWIYN34+DEK2cantq80oCOyhdbMjkwKXHOYzOhOhOD9QzKpXSCzqZWtkPumeSZ9abedikytYkXKJOJCmDjsmGtdLBBE76/cd6cCL65TJB/ZZZhQJn+Ma85mvT5KF4Xi+8uNIEMfeDTnQ827ul33jg1jE6iXo/mQL5SwbW401K37Hcess=
script:
- src/build/run-ci-build.sh
deploy:
  provider: releases
  api_key:
    secure: HPGN8lvadOQuquM0iJDj3h8zPtjT+r7h0OvP0bNXe8cXaQlKqIxxJ0iCKa1JTi/ByI9Pw5QUIcUfRkTHb24M79hCukO/TPxL3z8VdXzwFj2+wq8Zs/epkqQU+RNXLk1sDeaCJGgBNqP8zBkn9wNOfOEgcWJGUBWkMEyI/RFaXUnC9SC/nTospfmPkQu4OOl30uk5KNd5HudwJ7Xsc5EhoILYfzoJx7+GYZzt463xUWNpgC/kLCA9Ii0iCzH7zxO4ifCEfJdX5SvLzvHy5ox7tDhbL1pE3R2hg23NSC6sO3a0iS7iaOzpTuFMoybcGhB+w/EPbUfTBcEOJ/2ycSnMH/bNQIsjYrHGKhvQ7dPW4HwhoKXI8mf+sdnDOqvQZLnxgRydz7T9ed/z3bJU5H3hRAJgFXkfsAKKVedpRAC68gZzW//gZboYwP6eg6pMrqFpCZao+/mym/nvSb41Kt5V36ajlYXF881n2luN41uIGxkcUjHCsmnUrfxUzMDsztobAhKZhNwkZqVg0YVGZPvSHgyuNQ+rCySaXD+Lye4vr6C719YsN0dsmWw9mwzcVlpI4M9BeHsRGG4YaQob7AMJCCQy8j1ggDyoE8nwcRHH2r2GPRxBYTuJvPcIxx1JB+peotvLm2Gl3JCet1mXrjyfbGdnvw7i02254W1DlbYPD9s=
  file:
  - install.sh
  #- install.ps1
  body:
  - "### Release Notes\n* test release note line 1\n* test release note line 2"
  skip_cleanup: true
  on:
    repo: appbricks/vpn-server
    tags: true
