#!/bin/bash

source $(dirname $BASH_SOURCE)/common
set -euo pipefail

working_dir=$1 && shift

echo -e "${GREEN}\nCreating control files in current folder...${NC}"

if [[ ! -e ${working_dir}/cloud-creds.sh ]]; then
  cat << ---EOF > ${working_dir}/cloud-creds.sh
# AWS IaaS credentials for Terraform
export AWS_ACCESS_KEY=
export AWS_SECRET_KEY=

# GCP IaaS credentials for Terraform
export GOOGLE_CREDENTIALS=
export GOOGLE_PROJECT=

# Azure IaaS credentials for Terraform
export ARM_USE_MSI=true
export ARM_SUBSCRIPTION_ID=
export ARM_TENANT_ID=
export ARM_CLIENT_ID=
export ARM_CLIENT_SECRET=
---EOF
fi

if [[ ! -e ${working_dir}/build-vars.sh ]]; then
  cat << ---EOF > ${working_dir}/build-vars.sh
# Deployment idenfifier or name
export TF_VAR_name=

# DNS Zone for all deployments
export TF_VAR_attach_dns_zone=false

# Uncomment only if attaching to a DNS zone
# - AWS DNS configuration
#export TF_VAR_aws_dns_zone=
# - Azure DNS configuration
#export TF_VAR_azure_dns_zone=
#export TF_VAR_azure_dns_zone_resource_group=
# - Google DNS configuration
#export TF_VAR_google_dns_managed_zone_name=
#export TF_VAR_google_dns_zone=

# Values to used for creating self-signed X509 certs
export TF_VAR_company_name="appbricks"
export TF_VAR_organization_name="appbricks dev"
export TF_VAR_locality="Boston"
export TF_VAR_province="MA"
export TF_VAR_country="US"

export TF_VAR_idle_shutdown_time=60

# One of ipsec/openvpn. For wireguard configuration
# use the Cloud-Builder client.
export TF_VAR_vpn_type=ipsec

export TF_VAR_vpn_users="user1|password1,user2|password2"
---EOF
fi
