#!/bin/bash

workspace_dir=$1 && shift
template_dir=$1 && shift
node_type=${1:-<NODE_TYPE>} && shift
cloud=${1:-<CLOUD>} && shift

source $(dirname $BASH_SOURCE)/common
set -euo pipefail

region=""

common::validate_workspace reinit_node
while [[ $# -gt 0 ]]; do
  case "$1" in
    -r|--region)
      region=$2
      shift
      ;;
    -d|--debug)
      set -x
      ;;
    -h|--help)
      usage::reinit_node
      exit 0
      ;;
    *)
      echo -e "${RED}\nERROR! Unknown option \"$1\".${NC}"
      usage::reinit_node
      exit 1
      ;;
  esac
  shift
done

if [[ -z $region ]]; then
  usage::reinit_node
  echo -e "${RED}\nERROR! Please provide a cloud region from the following list.${NC}"
  $(dirname $BASH_SOURCE)/show-regions $cloud
  exit 1
fi

# This is usually set at deploy but required in 
# order to reinitialize without prompting for input.
export TF_VAR_vpn_idle_action=""

if [[ -e ${workspace_dir}/${region} ]]; then
  pushd ${workspace_dir}/${region} >/dev/null 2>&1
  terraform::set_cloud_region "$node_type" "$cloud" "$region"
  terraform::init "$node_type" "$cloud" "$region" "$template_dir"
  popd >/dev/null 2>&1
else
  echo -e "${RED}\nERROR! Deployment workspace path does not exist. The region"
  echo -e "       provided may be invalid or the server may not have been deployed.${NC}"
fi
