#!/bin/bash

source $(dirname $BASH_SOURCE)/common
set -euo pipefail

function command_usage() {
  echo -e "${NC}\nUSAGE: vs show-regions ${BOLD}<CLOUD>${NORMAL}\n"
  echo -e "${LIGHT_BLUE}  This CLI command shows the regions that can be targeted for each of the supported clouds.${NC}"
}

cloud=${1:--h}
case $cloud in
  aws)
    echo -e "${GREEN}\nAvailable Amazon Web Services (AWS) Regions:${NC}\n" 
    aws ec2 describe-regions --query "Regions[].{Name:RegionName}" --output text | sort
    echo -e "${GREEN}\nMore detail can be found at the following link:"
    echo -e "${BLUE}- https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.RegionsAndAvailabilityZones.html"
    ;;
  google)
    echo -e "${GREEN}\nAvailable Google Cloud Regions:${NC}\n" 
    gcloud compute regions list | awk '$1 != "NAME" { print $1 }' | sort
    echo -e "${GREEN}\nMore detail can be found at the following link:"
    echo -e "${BLUE}- https://cloud.google.com/compute/docs/regions-zones/"
    ;;
  azure)
    echo -e "${GREEN}\nAvailable Microsoft Azure Regions:${NC}\n" 
    az account list-locations -o table | awk '$4 != "Name" && $0 !~ /^-.*/ { print substr($0, 48) }' | sort
    echo -e "${GREEN}\nMore detail can be found at the following link:"
    echo -e "${BLUE}- https://cloud.google.com/compute/docs/regions-zones/"
    ;;
  -h|--help)
    command_usage
    exit 0
    ;;
  *)
    echo -e "${RED}\nERROR! Unknown cloud \"$cloud\".${NC}"
    command_usage
    exit 1
esac