#!/bin/bash

source $(dirname $BASH_SOURCE)/common
set -euo pipefail

cloud=${1:-help}
case $cloud in
  aws)
    common::validate_cloud_credentials $cloud
    set -euo pipefail

    echo -e "${GREEN}\nAvailable Amazon Web Services (AWS) Regions:${NC}\n" 
    cloud::set_aws_credentials
    aws ec2 describe-regions --query "Regions[].{Name:RegionName}" --output text | sort
    echo -e "${GREEN}\nMore detail can be found at the following link:"
    echo -e "${BLUE}- https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.RegionsAndAvailabilityZones.html"
    ;;
  azure)
    common::validate_cloud_credentials $cloud
    set -euo pipefail

    echo -e "${GREEN}\nAvailable Microsoft Azure Regions:${NC}\n" 
    cloud::set_azure_credentials
    az account list-locations | jq -r '.[].name' | sort
    echo -e "${GREEN}\nMore detail can be found at the following link:"
    echo -e "${BLUE}- https://azure.microsoft.com/en-us/global-infrastructure/locations/"
    ;;
  google)
    common::validate_cloud_credentials $cloud
    set -euo pipefail

    echo -e "${GREEN}\nAvailable Google Cloud Regions:${NC}\n" 
    cloud::set_google_credentials >/dev/null
    gcloud compute regions list | awk '$1 != "NAME" { print $1 }' | sort
    echo -e "${GREEN}\nMore detail can be found at the following link:"
    echo -e "${BLUE}- https://cloud.google.com/compute/docs/regions-zones/"
    ;;
  -h|--help|help)
    usage::show_regions
    exit 0
    ;;
  *)
    echo -e "${RED}\nERROR! Unknown cloud \"$cloud\".${NC}"
    usage::show_regions
    exit 1
esac