name: MyCS Cookbook and SDK (appbricks/vpn-server:dev) CLI
concurrency: dev

on:
  workflow_dispatch:
  push:
    branches: [ dev ]
    paths:
    - 'bin/**'
    - 'cloud/**'
    - 'src/**'
    - 'Dockerfile'

jobs:
  build-cookbook-utils:
    strategy:
      matrix:
        os: [ linux, darwin, windows ]
        arch: [ amd64, arm64 ]
        exclude:
          - os: windows
            arch: arm64

    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
      ENV: dev

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: '^1.20'

    - name: Run build
      run: |
        src/build/build-utils.sh :release:clean-all: ${{ matrix.os }} ${{ matrix.arch }}

    - name:  Upload dev binaries to S3
      run: |
        mkdir releases
        cp -r .build/releases/*.zip releases/
        aws s3 sync releases s3://mycs${ENV}-deploy-artifacts/releases --acl public-read

  build-and-publish-image:
    needs: build-cookbook-utils
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Retrieve latest appbricks cloud image name
      id: get_cloud_image
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1
      run: |
        CLOUD_IMAGE_NAME=$(./src/build/get-cloud-image.sh)
        echo "name=${CLOUD_IMAGE_NAME}" >> $GITHUB_OUTPUT

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        build-args: |
          env=dev
          version=dev
          ab_cloud_image=${{ steps.get_cloud_image.outputs.name }}
        push: true
        platforms: linux/amd64,linux/arm64
        tags: appbricks/vpn-server:dev
